// Auto-generated by scripts/fetch-trophies.mjs. The copero CDN only carries
// seven trophies (see lib/career/trophies.ts); everything else is resolved from
// Wikipedia and hotlinked, since these images are non-free. Anything missing
// falls back to the drawn icon in components/career/TrophyArt.tsx.
// The World Cup award keys are deliberately absent: Wikipedia returns a press
// photo of that year's winner rather than the award, which looks wrong next to
// real trophy art, so they use the drawn icons instead.
export const TROPHY_WIKI: Record<string, string> = {
  "euro": "https://upload.wikimedia.org/wikipedia/commons/8/81/Coupe_Henri_Delaunay_2017.jpg",
  "asian-cup": "https://upload.wikimedia.org/wikipedia/en/4/4d/AFC_Asian_Cup.png",
  "afcon": "https://upload.wikimedia.org/wikipedia/en/c/cf/Africa_Cup_of_Nation_official_logo.png",
  "gold-cup": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Concacaf_Gold_Cup_2021.svg",
  "nations-league": "https://upload.wikimedia.org/wikipedia/en/8/80/UEFA_Nations_League.svg",
  "concacaf-cup": "https://upload.wikimedia.org/wikipedia/commons/3/3e/CONCACAF_Champions_Cup_logo.svg",
  "afc-cl": "https://upload.wikimedia.org/wikipedia/en/d/d7/AFC_Champions_League_Elite_logo.svg",
  "caf-cl": "https://upload.wikimedia.org/wikipedia/en/d/d5/CAF_Champions_League.png",
  "ballon-dor": "https://upload.wikimedia.org/wikipedia/commons/0/04/2016_Ballon_dOr_CR7Museum.jpg",
  "the-best": "https://upload.wikimedia.org/wikipedia/commons/0/03/The_Best_FIFA_Football_Awards.svg",
  "golden-shoe": "https://upload.wikimedia.org/wikipedia/en/2/2b/Golden_Shoe%2C_Lionel_Messi_2012-2013.jpg",
};
